name: Deploy Plugin to GitHub Pages

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
        # Fica na raiz para o deploy funcionar

      - name: Checkout Player
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/vlibras-player-webjs
          ref: dev
          path: player-folder # Baixa dentro de uma subpasta segura

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build
        run: |
          # 1. Buildar o Player
          cd player-folder
          npm install --legacy-peer-deps
          npm run build
          
          # 2. Voltar para o Plugin e forçar a instalação do player local
          cd ..
          npm install --legacy-peer-deps
          
          # TRUQUE: Sobrescreve a dependência "file:../" pelo caminho real da Action
          npm install ./player-folder --legacy-peer-deps
          
          # 3. Build do Plugin
          npm run build

      - name: Prepare Assets
        run: touch widget/app/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: widget/app
          branch: gh-pages
          clean: true